apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: balloon-web
  name: balloon-web
  namespace: balloon
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: balloon-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: balloon-web
    spec:
      containers:
      - image: gyselroth/balloon-web:3.0.0-beta1
        imagePullPolicy: Always
        name: balloon-web
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: "0"
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config-volume
          subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: balloon-web-nginx-config
        name: nginx-config-volume
