apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: chrome
  namespace: balloon
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: chrome
  targetCPUUtilizationPercentage: 80
