apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: chrome
  name: chrome
  namespace: balloon
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    k8s-app: chrome
  sessionAffinity: None
  type: ClusterIP
