apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: es-client
  namespace: balloon
  labels:
    component: elasticsearch
    role: client
    k8s-app: elasticsearch
spec:
  replicas: 6
  template:
    metadata:
      labels:
        component: elasticsearch
        role: client
        k8s-app: elasticsearch
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - client
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-client
        image: elasticsearch:6.6.1
        command:
        - sh
        - -c
        - "echo xpack.security.enabled: false >> /usr/share/elasticsearch/config/elasticsearch.yml; elasticsearch-plugin install --batch https://balloon.gyselroth.net/share/b7a9451cbb7731ed283a1b9c4b41c0b3; /usr/local/bin/docker-entrypoint.sh elasticsearch"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "cluster.name"
          value: syslog
        - name: "node.master"
          value: "false"
        - name: "discovery.zen.ping.unicast.hosts"
          value: "elasticsearch-discovery"
        - name: node.data
          value: "false"
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m
        - name: "xpack.security.enabled"
          value: "false"
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          limits:
            cpu: 1
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/readonlyrest.yml
          subPath: readonlyrest.yml
      volumes:
          - emptyDir:
              medium: ""
            name: storage
          - name: elasticsearch-config
            configMap:
              name: elasticsearch-config
