apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-data
  namespace: balloon
  labels:
    component: elasticsearch
    role: data
    k8s-app: elasticsearch
spec:
  serviceName: elasticsearch-data
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
        k8s-app: elasticsearch
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - data
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-data
        image: elasticsearch:6.6.1
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "cluster.name"
          value: syslog
        - name: node.master
          value: "false"
        - name: node.ingest
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: "discovery.zen.ping.unicast.hosts"
          value: "elasticsearch-discovery"
        - name: "xpack.security.enabled"
          value: "false"
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          limits:
            cpu: 2
        ports:
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: es-data-storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: es-data-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "generic-nimble"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
