apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  namespace: balloon
  labels:
    component: elasticsearch
    role: data
    k8s-app: elasticsearch
spec:
  ports:
  - port: 9300
    name: transport
  selector:
    component: elasticsearch
    role: data
