apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-ingest
  namespace: balloon
  labels:
    component: elasticsearch
    role: ingest
spec:
  selector:
    component: elasticsearch
    role: ingest
  ports:
  - name: http
    port: 9200
#type: LoadBalancer
