apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    k8s-app: libreoffice
  name: libreoffice
  namespace: balloon
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: libreoffice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimesdomainp: null
      labels:
        k8s-app: libreoffice
    spec:
      containers:
      - env:
        - name: domain
          value: web
        image: collabora/code
        imagePullPolicy: IfNotPresent
        name: libreoffice
        ports:
        - containerPort: 9980
          protocol: TCP
        resources:
          limits:
            cpu: 800m
            memory: 470Mi
          requests:
            cpu: "0"
            memory: 190Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/loolwsd/cert.pem
          name: tls-crt
          readOnly: true
          subPath: cert.pem
        - mountPath: /etc/loolwsd/key.pem
          name: tls-key
          readOnly: true
          subPath: key.pem
        - mountPath: /etc/loolwsd/ca-chain.cert.pem
          name: tls-chain
          readOnly: true
          subPath: ca-chain.cert.pem
        - mountPath: /etc/loolwsd/loolwsd.xml
          name: libreoffice-config
          readOnly: true
          subPath: loolwsd.xml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tls-crt
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: cert.pem
          secretName: tls-domain.ch
      - name: tls-key
        secret:
          defaultMode: 420
          items:
          - key: tls.key
            path: key.pem
          secretName: tls-domain.ch
      - configMap:
          defaultMode: 420
          items:
          - key: chain.crt
            path: ca-chain.cert.pem
          name: tls-chain-domain.ch
        name: tls-chain
      - configMap:
          defaultMode: 420
          items:
          - key: loolwsd.xml
            path: loolwsd.xml
          name: libreoffice-config
        name: libreoffice-config
