mongodb:
    image: mongo:3.6
clamav:
    image: dinkel/clamavd:latest
libreoffice:
    image: collabora/code:4.0.1.1
    ports:
        - "9980:9980"
    links:
        - balloon-dev
    environment:
        - domain=balloon-dev
    entrypoint:
        - sh
        - -c
        - "sed s/::1/::ffff:172.[0-9]+.[0-9]+.[0-9]+/g /etc/loolwsd/loolwsd.xml -i; bash /start-libreoffice.sh"
elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    #entrypoint:
        #- /bin/sh
        #- -c
        #- "elasticsearch-plugin install --batch ingest-attachment && docker-entrypoint.sh"
postfix:
    image: webuni/postfix
browserless:
    image: browserless/chrome
balloon-dev-jobs:
    image: gyselroth/balloon-development:latest
    volumes:
        - .:/srv/www/balloon
    #entrypoint: php /srv/www/balloon/src/cgi-bin/cli.php jobs -vvvv -f
    links:
        - clamav
        - mongodb
          #- elasticsearch
        - postfix
        - browserless
        - libreoffice
    environment:
        - BALLOON_MONGODB_URI=mongodb://mongodb:27017
        - BALLOON_CLAMAV_URI=tcp://clamav:3310
        - BALLOON_ELASTICSEARCH_URI=http://elasticsearch:9200
        - BALLOON_WOPI_URL=https://balloon-dev
        - BALLOON_SMTP_HOST=postfix
        - BALLOON_URL=http://localhost:8080
        - BALLOON_BURL_BROWSERLESS_URL=http://browserless:3000
balloon-dev:
    image: gyselroth/balloon-development:latest
    ports:
        - "8081:443"
    volumes:
        - .:/srv/www/balloon
    links:
        - clamav
        - mongodb
        - elasticsearch
        - postfix
        - browserless
    environment:
        - BALLOON_MONGODB_URI=mongodb://mongodb:27017
        - BALLOON_CLAMAV_URI=tcp://clamav:3310
        - BALLOON_ELASTICSEARCH_URI=http://elasticsearch:9200
        - BALLOON_WOPI_URL=https://balloon-dev
        - BALLOON_SMTP_HOST=postfix
        - BALLOON_URL=http://localhost:8080
        - BALLOON_BURL_BROWSERLESS_URL=http://browserless:3000
