version: '2'
networks:
    backend:
    frontend:

services:
    mongodb:
        image: mongo:3.6
        networks:
        - backend
    clamav:
        image: dinkel/clamavd:latest
        networks:
        - backend
    libreoffice:
        image: collabora/code:4.0.4.3
        ports:
            - "9980:9980"
        environment:
         - domain=balloon-web\|balloon-dev\|localhost
         - extra_params=--o:ssl.termination=false --o:ssl.enable=false --o:net.post_allow.host[0]=::ffff:172.[0-9]+.[0-9]+.[0-9]+ --o:storage.wopi.host[2]=::ffff:172.[0-9]+.[0-9]+.[0-9]+ --o:net.frame_ancestors="localhost:* balloon-web:*"
        networks:
        - backend
        - frontend
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
        entrypoint:
            - /bin/sh
            - -c
            - "elasticsearch-plugin list | grep ingest-attachment || elasticsearch-plugin install ingest-attachment --batch && docker-entrypoint.sh"
        networks:
        - backend
    postfix:
        image: webuni/postfix
        networks:
        - backend
    browserless:
        image: browserless/chrome
        networks:
        - backend
    balloon-dev-jobs:
        image: gyselroth/balloon:latest-dev
        volumes:
            - .:/srv/www/balloon
        networks:
        - backend
        environment:
            - BALLOON_MONGODB_URI=mongodb://mongodb:27017
            - BALLOON_CLAMAV_URI=tcp://clamav:3310
            - BALLOON_LIBREOFFICE_CONVERT_URL=http://libreoffice:9980
            - BALLOON_LIBREOFFICE_COLLAB_URL=http://libreoffice:9980
            - BALLOON_LIBREOFFICE_COLLAB_WOPI_URL=http://balloon-web/wopi
            - BALLOON_SMTP_HOST=postfix
            - BALLOON_URL=http://localhost:8084
            - BALLOON_BURL_BROWSERLESS_URL=http://browserless:3000
            - BALLOON_LOG_LEVEL=100
            - BALLOON_TASK_WORKER_PM=ondemand
            - BALLOON_ELASTICSEARCH_URI=http://elasticsearch:9200
    balloon-web:
        image: gyselroth/balloon-web:latest
        ports:
            - "8084:80"
        links:
            - balloon-dev
        volumes:
            - ${PWD}/packaging/docker-dev/:/etc/nginx/conf.d
        networks:
        - backend
        - frontend
    balloon-dev:
        image: gyselroth/balloon:latest-dev
        volumes:
            - .:/srv/www/balloon
        networks:
        - backend
        environment:
            - BALLOON_MONGODB_URI=mongodb://mongodb:27017
            - BALLOON_CLAMAV_URI=tcp://clamav:3310
            - BALLOON_ELASTICSEARCH_URI=http://elasticsearch:9200
            - BALLOON_LIBREOFFICE_CONVERT_URL=http://libreoffice:9980
            - BALLOON_LIBREOFFICE_COLLAB_URL=http://libreoffice:9980
            - BALLOON_LIBREOFFICE_COLLAB_WOPI_URL=http://balloon-web/wopi
            - BALLOON_SMTP_HOST=postfix
            - BALLOON_URL=http://localhost:8084
            - BALLOON_LOG_LEVEL=100
            - BALLOON_TASK_WORKER_PM=ondemand
            - BALLOON_BURL_BROWSERLESS_URL=http://browserless:3000
