FROM php:7.2-fpm

RUN apt-get update && apt-get install -y \
  libldb-dev \
  libldap2-dev \
  libxml2-dev \
  libcurl4-openssl-dev \
  libssl-dev \
  libzip-dev \
  libicu-dev \
  libsmbclient-dev \
  gnupg \
  nginx \
  git \
  make \
  rsync \
  curl \
  libmagickwand-dev \
  && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/libldap.so
RUN docker-php-ext-install ldap xml opcache curl zip intl sockets pcntl sysvmsg

RUN pecl install mongodb \
    && pecl install apcu \
    && pecl install imagick \
    && pecl install smbclient \
    && docker-php-ext-enable mongodb apcu imagick smbclient pcntl

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && echo "xdebug.overload_var_dump=0" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && ln -s /srv/www/balloon/config/php.ini /usr/local/etc/php/conf.d/zz-custom.ini

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
  && php composer-setup.php --filename=composer --install-dir=/usr/bin \
  && php -r "unlink('composer-setup.php');"

RUN mkdir /etc/ssl/balloon \
  && openssl genrsa -des3 -passout pass:x12345 -out server.pass.key 2048 \
  && openssl rsa -passin pass:x12345 -in server.pass.key -out key.pem \
  && rm server.pass.key \
  && openssl req -new -key key.pem -out server.csr -subj "/C=CH//L=Zurich/O=Balloon/CN=balloon.local" \
  && openssl x509 -req -days 365 -in server.csr -signkey key.pem -out chain.pem \
  && rm server.csr \
  && mv key.pem /etc/ssl/balloon/ \
  && mv chain.pem /etc/ssl/balloon/

COPY packaging/docker-dev/nginx.conf /etc/nginx/conf.d

EXPOSE 80 443

CMD make -C /srv/www/balloon deps; \
  php /srv/www/balloon/src/cgi-bin/cli.php upgrade start -i; \
  service nginx start && php-fpm
