web:
    image: gyselroth/balloon-web:2.0.0-rc1
    ports:
        - "8082:443"
    links:
        - balloon
mongodb:
    image: mongo:3.6.0
clamav:
    image: dinkel/clamavd:latest
libreoffice:
    image: collabora/code
    ports:
        - "9980:9980"
    links:
        - balloon
    environment:
        - domain=balloon
elasticsearch:
    image: gyselroth/balloon-elasticsearch:latest
postfix:
    image: webuni/postfix
balloon:
    image: gyselroth/balloon:2.0.0-rc1
    links:
        - clamav
        - mongodb
        - elasticsearch
        - postfix
    entrypoint: php-fpm
    environment:
        - BALLOON_MONGODB_URI=mongodb://mongodb:27017
        - BALLOON_CLAMAV_URI=tcp://clamav:3310
        - BALLOON_ELASTICSEARCH_URI=http://elasticsearch:9200
        - BALLOON_WOPI_URL=https://balloon
        - BALLOON_SMTP_HOST=postfix
        - BALLOON_URL=http://localhost:8080
balloon-jobs:
    image: gyselroth/balloon:latest-unstable
    links:
        - clamav
        - mongodb
        - elasticsearch
        - postfix
    entrypoint: ballooncli jobs listen
    environment:
        - BALLOON_MONGODB_URI=mongodb://mongodb:27017
        - BALLOON_CLAMAV_URI=tcp://clamav:3310
        - BALLOON_ELASTICSEARCH_URI=http://elasticsearch:9200
        - BALLOON_WOPI_URL=https://balloon
        - BALLOON_SMTP_HOST=postfix
        - BALLOON_URL=http://localhost:8080

