mongodb:
    image: mongo:3.6.0
clamav:
    image: dinkel/clamavd:latest
libreoffice:
    image: collabora/code
    ports:
        - "9980:9980"
    links:
        - balloon-dev
elasticsearch:
    image: gyselroth/balloon-elasticsearch:latest
balloon-dev:
    image: gyselroth/balloon-development:latest
    ports:
        - "8081:443"
    volumes:
        - .:/srv/www/balloon
    links:
        - clamav
        - mongodb
        - elasticsearch
    environment:
        - BALLOON_MONGODB_URI=mongodb://mongodb:27017
        - BALLOON_CLAMAV_URI=tcp://clamav:3310
        - BALLOON_ELASTICSEARCH_URI=http://elasticsearch:9200
        - BALLOON_WOPI_URL=https://localhost:8081
