site_name: balloon
theme: material
extra_css:
- css/extra.css
markdown_extensions:
- markdown_include.include:
    base_path: .
nav:
- Home: index.md
- Server:
  - Installation: server/installation.md
  - Changelog: server/changelog.md
  - Upgrade: server/upgrade.md
  - Apps:
    - Elasticsearch: server/apps/elasticsearch.md
  - Development: server/development.md
- Web client:
  - index: web-client.md
  - Web client: development/web-client.md
- Desktop client: desktop-client.md
