#!/bin/bash
if [ ! -d /var/log/balloon ]; then
  mkdir /var/log/balloon
fi

if [ ! -h /usr/share/balloon/config ]; then
    ln -s /usr/share/balloon/config /etc/balloon
fi

if [ ! -h /usr/share/balloon/log ]; then
    ln -s /usr/share/balloon/log /var/log/balloon
fi

if [ ! -h /usr/bin/ballooncli ]; then
    ln -s /usr/share/balloon/bin/console/ballooncli /usr/bin/ballooncli
fi

if [[ ! -f /etc/systemd/system/balloon-jobs.service && -d /etc/systemd/system ]]; then
    cp /usr/share/balloon/scripts/balloon-jobs.service.systemd /etc/systemd/system/balloon-jobs.service
fi

if [[ ! -f /etc/init/balloon-jobs.conf && -d /etc/init ]]; then
    cp /usr/share/balloon/scripts/balloon-jobs.service.upstart /etc/init/balloon-jobs.conf
fi

/usr/bin/ballooncli upgrade -vvv -i
/usr/bin/ballooncli useradd -u admin -p admin -m root@localhost.local -a

systemctl enable balloon-jobs.service 2> /dev/null
service balloon-jobs restart
