version: '3'
networks:
  backend:
  frontend:

services:
  traefik:
    image: traefik:v1.7-alpine
    command: --web --docker --docker.domain=docker.localhost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
    - backend
    - frontend
  mongodb:
    image: mongo:3.6
    networks:
    - backend
  clamav:
    image: dinkel/clamavd:latest
    networks:
    - backend
  libreoffice:
    image: collabora/code:4.0.1.1
    ports:
      - "9980:9980"
    environment:
      - domain=balloon
      - extra_params=--o:ssl.termination=true --o:ssl.enable=false --o:net.post_allow.host[0]=::ffff:172.[0-9]+.[0-9]+.[0-9]+ --o:storage.wopi.host[2]=::ffff:172.[0-9]+.[0-9]+.[0-9]+
    networks:
    - backend
    - frontend
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    entrypoint:
      - /bin/sh
      - -c
      - "elasticsearch-plugin list | grep ingest-attachment || elasticsearch-plugin install ingest-attachment --batch && docker-entrypoint.sh"
    networks:
    - backend
  postfix:
    image: webuni/postfix
    networks:
    - backend
  browserless:
    image: browserless/chrome
    networks:
    - backend
  balloon-proxy:
    image: nginx
    networks:
    - backend
    command: |
      bash -c 'rm /etc/nginx/conf.d/default.conf; bash -s <<EOF
        cat > /etc/nginx/conf.d/balloon.conf <<EON
          server {
              listen 80;
              access_log /dev/stdout;
              error_log /dev/stderr;
              client_max_body_size 16G;

              location ~ ^/(api|webdav|share) {
                  index index.php;
                  root /usr/share/balloon/bin/httpdocs;
                  rewrite ^(.+)\\\$$ /index.php\\\$$1 last;
                  break;
              }

              location ~ ^/index.php {
                  root /usr/share/balloon/bin/httpdocs;
                  fastcgi_pass balloon:9000;
                  fastcgi_read_timeout 300;
                  fastcgi_param SCRIPT_FILENAME /usr/share/balloon/bin/httpdocs\\\$$fastcgi_script_name;
                  fastcgi_param PATH_INFO \\\$$fastcgi_script_name;
                  include /etc/nginx/fastcgi_params;
              }
          }
      EON
      nginx -g "daemon off;"
      EOF'
    labels:
    - traefik.backend=server
    - "traefik.frontend.rule=PathPrefix:/api,/webdav,/share"
  balloon-jobs:
    image: gyselroth/balloon:latest
    depends_on:
    - mongodb
    entrypoint: ballooncli jobs -vvvv
    networks:
    - backend
    environment:
      - BALLOON_MONGODB_URI=mongodb://mongodb:27017
      - BALLOON_CLAMAV_URI=tcp://clamav:3310
      - BALLOON_WOPI_URL=http://balloon
      - BALLOON_LIBREOFFICE_COLLAB_URL=http://libreoffice:9980
      - BALLOON_LIBREOFFICE_CONVERT_URL=http://libreoffice:9980
      - BALLOON_SMTP_HOST=postfix
      - BALLOON_URL=http://localhost:8080
      - BALLOON_BURL_BROWSERLESS_URL=http://browserless:3000
      - BALLOON_ELASTICSEARCH_URI=http://elasticsearch:9200
  balloon-web:
    image: gyselroth/balloon-web:latest
    networks:
    - backend
    - frontend
    labels:
    - traefik.backend=web
    - "traefik.frontend.rule=PathPrefix:/"
  balloon-upgrade:
    image: gyselroth/balloon:latest
    restart: on-failure
    entrypoint: ballooncli upgrade -vvvv
    networks:
    - backend
    environment:
      - BALLOON_MONGODB_URI=mongodb://mongodb:27017
      - BALLOON_CLAMAV_URI=tcp://clamav:3310
      - BALLOON_ELASTICSEARCH_URI=http://elasticsearch:9200
      - BALLOON_WOPI_URL=http://balloon
      - BALLOON_LIBREOFFICE_COLLAB_URL=http://libreoffice:9980
      - BALLOON_LIBREOFFICE_CONVERT_URL=http://libreoffice:9980
      - BALLOON_SMTP_HOST=postfix
      - BALLOON_URL=http://localhost:8080
      - BALLOON_BURL_BROWSERLESS_URL=http://browserless:3000
  balloon:
    image: gyselroth/balloon:latest
    entrypoint: php-fpm
    networks:
    - backend
    environment:
      - BALLOON_MONGODB_URI=mongodb://mongodb:27017
      - BALLOON_CLAMAV_URI=tcp://clamav:3310
      - BALLOON_ELASTICSEARCH_URI=http://elasticsearch:9200
      - BALLOON_WOPI_URL=http://balloon
      - BALLOON_LIBREOFFICE_COLLAB_URL=http://libreoffice:9980
      - BALLOON_LIBREOFFICE_CONVERT_URL=http://libreoffice:9980
      - BALLOON_SMTP_HOST=postfix
      - BALLOON_URL=http://localhost:8080
      - BALLOON_BURL_BROWSERLESS_URL=http://browserless:3000
