version: '3'
networks:
  backend:
  frontend:

services:
  traefik:
    image: traefik:v2.1
    command: --providers.docker --entrypoints.http.Address=:80 --entrypoints.https.Address=:443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - backend
    - frontend
  mongodb:
    image: mongo:3.6
    networks:
    - backend
  clamav:
    image: dinkel/clamavd:latest
    networks:
    - backend
  libreoffice-convert:
    image: collabora/code:4.2.0.3
    environment:
      - domain=localhost|balloon-proxy
      - extra_params=--o:ssl.termination=false --o:ssl.enable=false --o:net.post_allow.host[0]="::ffff:(172|192).[0-9]+.[0-9]+.[0-9]+" --o:storage.wopi.host[2]="::ffff:(172|192).[0-9]+.[0-9]+.[0-9]+"
    networks:
    - backend
  libreoffice-collab:
    image: collabora/code:4.2.0.3
    environment:
      - domain=localhost|balloon-proxy
      - extra_params=--o:ssl.termination=false --o:ssl.enable=false --o:net.post_allow.host[0]="::ffff:(172|192).[0-9]+.[0-9]+.[0-9]+" --o:net.service_root="/libreoffice" --o:storage.wopi.host[2]="::ffff:(172|192).[0-9]+.[0-9]+.[0-9]+" --o:net.frame_ancestors="localhost:*"
    networks:
    - backend
    - frontend
    labels:
    - "traefik.http.routers.loolwsd-http.rule=PathPrefix(`/libreoffice`)"
    - "traefik.http.routers.loolwsd-https.rule=PathPrefix(`/libreoffice`)"
    - "traefik.http.routers.loolwsd-https.tls"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.5
    entrypoint:
      - /bin/sh
      - -c
      - "elasticsearch-plugin list | grep ingest-attachment || elasticsearch-plugin install ingest-attachment --batch && docker-entrypoint.sh"
    networks:
    - backend
  postfix:
    image: webuni/postfix
    networks:
    - backend
  browserless:
    image: browserless/chrome:latest
    networks:
    - backend
  balloon-proxy:
    image: nginxinc/nginx-unprivileged:1-alpine
    networks:
    - backend
    command: |
      ash -c 'cat /etc/nginx/nginx.conf | sed -r "s/include \/etc\/nginx\/conf.d\/\*.conf\;/include \/tmp\/balloon\.conf;/g" > /tmp/nginx.conf; ash -s <<EOF
        cat > /tmp/balloon.conf <<EON
          server_tokens off;
          server {
              listen 8080;
              access_log /dev/stdout;
              error_log /dev/stderr;
              client_max_body_size 16G;

              location ~ ^/(api|webdav|share|wopi|healthz) {
                  index index.php;
                  root /usr/share/balloon/bin/httpdocs;
                  rewrite ^(.+)\\\$$ /index.php\\\$$1 last;
                  break;
              }

              location ~ ^/index.php {
                  root /usr/share/balloon/bin/httpdocs;
                  fastcgi_pass balloon-api:9000;
                  fastcgi_read_timeout 300;
                  fastcgi_param SCRIPT_FILENAME /usr/share/balloon/bin/httpdocs\\\$$fastcgi_script_name;
                  fastcgi_param PATH_INFO \\\$$fastcgi_script_name;
                  include /etc/nginx/fastcgi_params;
              }
          }
      EON
      nginx -c /tmp/nginx.conf -g "daemon off;"
      EOF'
    labels:
    - "traefik.http.routers.api-http.rule=PathPrefix(`/api`) || PathPrefix(`/webdav`) || PathPrefix(`/share`) || PathPrefix(`/wopi`) || PathPrefix(`/healthz`)"
    - "traefik.http.routers.api-https.rule=PathPrefix(`/api`) || PathPrefix(`/webdav`) || PathPrefix(`/share`) || PathPrefix(`/wopi`) || PathPrefix(`/healthz`)"
    - "traefik.http.routers.api-https.tls"
  balloon-jobs:
    image: gyselroth/balloon:latest
    depends_on:
    - mongodb
    entrypoint: ballooncli jobs -vvvv
    networks:
    - backend
    environment: &env
      - BALLOON_MONGODB_URI=mongodb://mongodb:27017
      - BALLOON_CLAMAV_URI=tcp://clamav:3310
      - BALLOON_ELASTICSEARCH_URI=http://elasticsearch:9200
      - BALLOON_LIBREOFFICE_COLLAB_URL=http://libreoffice-collab:9980/libreoffice
      - BALLOON_LIBREOFFICE_COLLAB_EXTERNAL_URL=http://localhost/libreoffice
      - BALLOON_LIBREOFFICE_COLLAB_WOPI_URL=http://balloon-proxy/wopi
      - BALLOON_LIBREOFFICE_CONVERT_URL=http://libreoffice-convert:9980
      - BALLOON_SMTP_HOST=postfix
      - BALLOON_URL=http://localhost:8080
      - BALLOON_BURL_BROWSERLESS_URL=http://browserless:3000
  balloon-web:
    image: gyselroth/balloon-web:latest
    networks:
    - backend
    - frontend
    labels:
    - "traefik.http.routers.webui-http.rule=PathPrefix(`/`)"
    - "traefik.http.routers.webui-https.rule=PathPrefix(`/`)"
    - "traefik.http.routers.webui-https.tls"
  balloon-upgrade:
    image: gyselroth/balloon:latest
    restart: on-failure
    entrypoint: ballooncli upgrade -vvvv
    networks:
    - backend
    environment: *env
  balloon-api:
    image: gyselroth/balloon:latest
    networks:
    - backend
    environment: *env
