#!/bin/bash

if [ $# -lt 2 ]; then
  echo "Usage: $0 USERNAME PASSWORD [admin]"
  exit 1
fi

admin=""
if [ "$3" == "admin" ]; then
  admin="admin: true, "
fi

balloonPassword=$(php -r "echo password_hash('$2', PASSWORD_DEFAULT);")
echo "db.user.insert({username: '$1', password: '$balloonPassword', $admin hard_quota : 100000000, soft_quota : 9999999});" > tmp.js
mongo balloon tmp.js
rm tmp.js
