paths:
  /oidc:
    post:
      tags:
        - oidc
      summary: Get OAUTH2 Bearer token
      operationId: createOidcToken
      consumes:
        - application/x-www-form-urlencoded
      produces:
      - "application/json"
      parameters:
        - in: formData
          name: grant_type
          description: "OAUTH2 grant_type"
          required: true
          type: string
          enum:
          - password
          - password_mfa
          - refresh_token
        - in: formData
          name: username
          description: "Username"
          required: false
          type: string
        - in: formData
          name: password
          description: "Password"
          required: false
          type: string
        - in: formData
          name: code
          description: "Multi factor value. This is usually some kind of a code."
          required: false
          type: string
        - in: formData
          name: refresh_token
          description: "OAUTH2 refresh_token to retrieve a new access_token."
          required: false
          type: string
      security:
      - BasicAuth: []
      responses:
        "200":
          description: Oauth2 token
          schema:
            $ref: "#/definitions/oidc.OAuth2Token"
        400:
          $ref: '#/responses/oidc.BadRequest'
        500:
          $ref: '#/responses/core.v3.InternalServerError'
responses:
  oidc.BadRequest:
    properties:
      error:
        description: "OAUTH2 error, see https://tools.ietf.org/html/rfc6749#section-5.2"
        type: string
      error_description:
        description: "Human-readable ASCII [USASCII] text providing additional information, used to assist the client developer in understanding the error that occurred."
        type: string
      error_uri:
        description: "A URI identifying a human-readable web page with information about the error, used to provide the client developer with additional information about the error."
        type: string
definitions:
  oidc.OAuth2Token:
    description: "OAUTH2 access token response according RFC6749 https://tools.ietf.org/html/rfc6749#section-4.3.3"
    type: object
    properties:
      access_token:
        description: Resource access_token.
        type: string
      expires_in:
        description: The number of seconds the issues acceess_token is valid for. This is usually 1hour.
        type: integer
        default: 3600
      token_type:
        description: The type of token. This is usually a Bearer token.
        type: string
        default: Bearer
      scope:
        description: The scopes.
        type: string
      refresh_token:
        description: An optional refresh token to get new access_tokens via the refresh_token grant type.
        type: string
